# Generated by Django 6.0.3 on 2026-03-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_netbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenserequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='expenserequest',
            name='department',
            field=models.CharField(choices=[('OfisiMchungaji', 'Ofisi Ya Mchungaji'), ('fedha', 'Finance'), ('elimu', 'Education'), ('afya', 'Afya'), ('huduma', 'Huduma Binafsi'), ('vijana', 'Vijana'), ('wanawake', 'Wana wa kike'), ('uwakili', 'Uwakili'), ('majengo', 'Majengo'), ('mawasiliano', 'Mawasiliano'), ('atape', 'Atape'), ('ss', 'SS'), ('newstart', 'New Start'), ('familia', 'Huduma za Familia'), ('vbs', 'VBS'), ('muziki', 'Muziki'), ('maombi', 'Maombi'), ('vop', 'VOP'), ('fedha', 'Fedha'), ('watoto', 'Watoto'), ('uchapaji', 'Uchapaji'), ('mahitaji', 'Mahitaji Maalumu'), ('amo&dorcas', 'AMO & Dorcas'), ('kwaya', 'Kwaya ya Kanisa'), ('syc', 'SYC'), ('shadow', ' Shadow of Calvary'), ('mashemasi', 'Mashemasi'), ('nyingineyo', 'Nyingineyo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='income',
            name='department',
            field=models.CharField(blank=True, choices=[('OfisiMchungaji', 'Ofisi Ya Mchungaji'), ('fedha', 'Finance'), ('elimu', 'Education'), ('afya', 'Afya'), ('huduma', 'Huduma Binafsi'), ('vijana', 'Vijana'), ('wanawake', 'Wana wa kike'), ('uwakili', 'Uwakili'), ('majengo', 'Majengo'), ('mawasiliano', 'Mawasiliano'), ('atape', 'Atape'), ('ss', 'SS'), ('newstart', 'New Start'), ('familia', 'Huduma za Familia'), ('vbs', 'VBS'), ('muziki', 'Muziki'), ('maombi', 'Maombi'), ('vop', 'VOP'), ('fedha', 'Fedha'), ('watoto', 'Watoto'), ('uchapaji', 'Uchapaji'), ('mahitaji', 'Mahitaji Maalumu'), ('amo&dorcas', 'AMO & Dorcas'), ('kwaya', 'Kwaya ya Kanisa'), ('syc', 'SYC'), ('shadow', ' Shadow of Calvary'), ('mashemasi', 'Mashemasi'), ('nyingineyo', 'Nyingineyo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='netbalance',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='retirement',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='retirement',
            name='department',
            field=models.CharField(choices=[('OfisiMchungaji', 'Ofisi Ya Mchungaji'), ('fedha', 'Finance'), ('elimu', 'Education'), ('afya', 'Afya'), ('huduma', 'Huduma Binafsi'), ('vijana', 'Vijana'), ('wanawake', 'Wana wa kike'), ('uwakili', 'Uwakili'), ('majengo', 'Majengo'), ('mawasiliano', 'Mawasiliano'), ('atape', 'Atape'), ('ss', 'SS'), ('newstart', 'New Start'), ('familia', 'Huduma za Familia'), ('vbs', 'VBS'), ('muziki', 'Muziki'), ('maombi', 'Maombi'), ('vop', 'VOP'), ('fedha', 'Fedha'), ('watoto', 'Watoto'), ('uchapaji', 'Uchapaji'), ('mahitaji', 'Mahitaji Maalumu'), ('amo&dorcas', 'AMO & Dorcas'), ('kwaya', 'Kwaya ya Kanisa'), ('syc', 'SYC'), ('shadow', ' Shadow of Calvary'), ('mashemasi', 'Mashemasi'), ('nyingineyo', 'Nyingineyo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('OfisiMchungaji', 'Ofisi Ya Mchungaji'), ('fedha', 'Finance'), ('elimu', 'Education'), ('afya', 'Afya'), ('huduma', 'Huduma Binafsi'), ('vijana', 'Vijana'), ('wanawake', 'Wana wa kike'), ('uwakili', 'Uwakili'), ('majengo', 'Majengo'), ('mawasiliano', 'Mawasiliano'), ('atape', 'Atape'), ('ss', 'SS'), ('newstart', 'New Start'), ('familia', 'Huduma za Familia'), ('vbs', 'VBS'), ('muziki', 'Muziki'), ('maombi', 'Maombi'), ('vop', 'VOP'), ('fedha', 'Fedha'), ('watoto', 'Watoto'), ('uchapaji', 'Uchapaji'), ('mahitaji', 'Mahitaji Maalumu'), ('amo&dorcas', 'AMO & Dorcas'), ('kwaya', 'Kwaya ya Kanisa'), ('syc', 'SYC'), ('shadow', ' Shadow of Calvary'), ('mashemasi', 'Mashemasi'), ('nyingineyo', 'Nyingineyo')], max_length=50),
        ),
    ]
