# Generated by Django 6.0.3 on 2026-03-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_expenserequest_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultdaterange',
            name='from_date',
            field=models.DateField(blank=True, help_text='Optional: Start date for a fixed range', null=True),
        ),
        migrations.AddField(
            model_name='defaultdaterange',
            name='to_date',
            field=models.DateField(blank=True, help_text='Optional: End date for a fixed range', null=True),
        ),
    ]
